msg = "narayan"
print(msg)
print(msg)
print(msg)
print(msg)
print(msg)
print(msg)
print("hello Piyush")
print(msg)
print(msg)
print(msg)
print(msg)
print(msg)
abc = msg.capitalize()
print("my name is ",abc,"\n hello welcome")
